export const UNLOCKS = {
  AutoUnlock: "auto_unlock",
  Cactus: "cactus",
  Carrots: "carrots",
  Costs: "costs",
  Debug: "debug",
  Debug_2: "debug_2",
  Dictionaries: "dictionaries",
  Snake: "snake",
  Expand: "expand",
  Fertilizer: "fertilizer",
  Functions: "functions",
  Grass: "grass",
  Dino: "dino",
  Import: "import",
  Leaderboard: "leaderboard",
  Lists: "lists",
  Loops: "loops",
  Mazes: "mazes",
  Megafarm: "megafarm",
  Operators: "operators",
  Plant: "plant",
  Polyculture: "polyculture",
  Pumpkins: "pumpkins",
  Senses: "senses",
  Simulation: "simulation",
  Speed: "speed",
  Sunflowers: "sunflowers",
  Remains: "remains",
  Timing: "timing",
  TopHat: "top_hat",
  Trees: "trees",
  Utilities: "utilities",
  Variables: "variables",
  Watering: "watering",

};

export const UNLOCKS_NAME_ZH = {
  [UNLOCKS.AutoUnlock]: "自动解锁",
  [UNLOCKS.Cactus]: "仙人掌",
  [UNLOCKS.Carrots]: "胡萝卜",
  [UNLOCKS.Costs]: "成本",
  [UNLOCKS.Debug]: "调试",
  [UNLOCKS.Debug_2]: "调试高级",
  [UNLOCKS.Dictionaries]: "字典（对象）",
  [UNLOCKS.Snake]: "蛇模式",
  [UNLOCKS.Expand]: "世界扩展",
  [UNLOCKS.Fertilizer]: "肥料",
  [UNLOCKS.Functions]: "函数",
  [UNLOCKS.Grass]: "草",
  [UNLOCKS.Dino]: "恐龙",
  [UNLOCKS.Import]: "导入功能",
  [UNLOCKS.Leaderboard]: "排行榜",
  [UNLOCKS.Lists]: "列表（数组）",
  [UNLOCKS.Loops]: "循环",
  [UNLOCKS.Mazes]: "迷宫",
  [UNLOCKS.Megafarm]: "巨型农场",
  [UNLOCKS.Operators]: "运算符",
  [UNLOCKS.Plant]: "种植",
  [UNLOCKS.Polyculture]: "多种栽培",
  [UNLOCKS.Pumpkins]: "南瓜",
  [UNLOCKS.Senses]: "感知能力",
  [UNLOCKS.Simulation]: "模拟",
  [UNLOCKS.Speed]: "速度",
  [UNLOCKS.Sunflowers]: "向日葵",
  [UNLOCKS.Remains]: "残余",
  [UNLOCKS.Timing]: "计时",
  [UNLOCKS.TopHat]: "高礼帽皮肤",
  [UNLOCKS.Trees]: "树",
  [UNLOCKS.Utilities]: "工具库",
  [UNLOCKS.Variables]: "变量",
  [UNLOCKS.Watering]: "浇水",
};


export const CROP_TYPE_NAMES = {
  Cactus: "仙人掌",
  Carrots: "胡萝卜",
  Pumpkins: "南瓜",
  Sunflowers: "向日葵",
  Trees: "树",
  Grass: "草",
  Bush: "灌木丛",
  
};

/*potato: 0,
      peanut: 0,
      pumpkin: 0,
      straw: 0,
      gold : 0,
      apple:0,
      hay:0,
      wood:0,
      carrot:0,
      cactus:0,
      sunflower:0, */
export const CROP_TYPE_ITEM_MAPPING = {
  Cactus: "cactus",
  Carrots: "carrot",
  Pumpkins: "pumpkin",
  Sunflowers: "sunflower",
  Trees: "wood",
  Grass: "hay",
  Bush: "wood",
}

export const DIRECTIONS = {
  Up: "up",
  Down: "down",
  Left: "left",
  Right: "right",
};

export const CHARACTER_TYPES = {
  snake: "snake",
  dino: "dino",
  drone: "drone",
};

export default {
  UNLOCKS,
  CROP_TYPE_NAMES,
  DIRECTIONS,
  CHARACTER_TYPES,
  CROP_TYPE_ITEM_MAPPING,
  UNLOCKS_NAME_ZH,
}